### ISSUE TITLE
[Bug] Interface elements are misplaced when module is enabled

### ISSUE THREAD

**Issue by r-valyar** [ironmonk88/monks-player-settings#6]
When the module is enabled (I am using Tiny UI always enabled), all interface elements are no longer neatly aligned:

With Player Settings enabled:
![image](https://user-images.githubusercontent.com/63558984/178954658-fa9a5f02-6a6b-416a-bb61-55dfc7da8c15.png)

How it should be:
![image](https://user-images.githubusercontent.com/63558984/178954682-e56b8d7b-f93d-47df-97ec-ef21ba1d7813.png)

**Comment by dmaneyapanda** [comment]
I also find it is pushing the Save button off the bottom of the screen for me.  A tiny sliver is available to click on.

How it looks with this module disabled:
<img width="463" alt="image" src="https://user-images.githubusercontent.com/2231877/185276347-53a461b4-8da3-419b-8f16-315cba75ab36.png">

How it looks when enabled:
<img width="461" alt="image" src="https://user-images.githubusercontent.com/2231877/185276461-0b1f8f90-4bdf-4aae-80fb-e9b6af39411c.png">

This is running on windows, and there is a windows bar always on.  Possibly it is calculating the screen size instead of the available window size when deciding where to put the buttons?

**Comment by dmaneyapanda** [comment]
Or possibly it's not including the size of the new player dropdown for selecting which player's settings you're looking at.

I also just noticed there is a second scrollbar there which, if you can get your mouse exactly right and grab it, will scroll the buttons into view.

**Comment by ironmonk88** [comment]
I think this was an issue with Tiny UI and MPS not playing nicely together and not resizing the window properly after elements have been added.
Since MPS is only getting updates in v10... I think this ticket is no longer applicable, since the settings interface for v10 has completely changed.
